language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

notifications:
  email: false

addons:
  code_climate:
    repo_token: 24890aa99b796be983cd8569fd2a2e0f7d2e6196175a15d4dfd2c77533a9e577

install:
  - composer install --dev --no-interaction
script:
  - phpunit --configuration .phpunit.xml --verbose
after_script:
  - vendor/bin/test-reporter
